
package com.voiceobjects.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSProvider", targetNamespace = "http://webservices.voiceobjects.com", wsdlLocation = "file:/home/ericp/Downloads/voxeo.wsdl")
public class WSProvider
    extends Service
{

    private final static URL WSPROVIDER_WSDL_LOCATION;
    private final static WebServiceException WSPROVIDER_EXCEPTION;
    private final static QName WSPROVIDER_QNAME = new QName("http://webservices.voiceobjects.com", "WSProvider");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.voxeo.com/vo-proxy/VoxeoCXP/md/Services/WSProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPROVIDER_WSDL_LOCATION = url;
        WSPROVIDER_EXCEPTION = e;
    }

    public WSProvider() {
        super(__getWsdlLocation(), WSPROVIDER_QNAME);
    }

    public WSProvider(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPROVIDER_QNAME, features);
    }

    public WSProvider(URL wsdlLocation) {
        super(wsdlLocation, WSPROVIDER_QNAME);
    }

    public WSProvider(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPROVIDER_QNAME, features);
    }

    public WSProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSProvider(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSProviderPortType
     */
    @WebEndpoint(name = "WSProviderHttpPort")
    public WSProviderPortType getWSProviderHttpPort() {
        return super.getPort(new QName("http://webservices.voiceobjects.com", "WSProviderHttpPort"), WSProviderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSProviderPortType
     */
    @WebEndpoint(name = "WSProviderHttpPort")
    public WSProviderPortType getWSProviderHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.voiceobjects.com", "WSProviderHttpPort"), WSProviderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPROVIDER_EXCEPTION!= null) {
            throw WSPROVIDER_EXCEPTION;
        }
        return WSPROVIDER_WSDL_LOCATION;
    }

}
